minio:
  endpoint: https://play.min.io
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false
  bucket-name: nicat
  file-size: 10485760
  image-size: 1073741824
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


